apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vv02yfi7k-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vv02yfi7k-java-quarkus-gitops